server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hawk_db?serverTimezone=CST
    username: root
    password: colin123.
    driver-class-name: com.mysql.cj.jdbc.Driver



